# -*- coding: utf-8 -*-
"""UsingSignBoards.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2Gpy_tvfNLUvY_5AH7CLyJDB03LiQAQ
"""

try:
    from PIL import Image
except ImportError:
    import Image
from googletrans import Translator
import easyocr
import numpy as np
import matplotlib.pyplot as plt
reader = easyocr.Reader(['ar', 'en'])
translator = Translator()

def translate(result):
    text = ''
    for op in result:
        tr = translator.detect(op)
        if tr.lang=='ar':
            text += op
    return translator.translate(text).text

def translate_from_image(image_path, to_plot=False):
    result = reader.readtext(image_path, detail=0)
    if to_plot:
        image = Image.open(image_path)
        plt.imshow(image)
        plt.show()
    # print(result)
    return translate(result)